# Generated by Django 5.1.1 on 2024-09-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review_email_review_image_review_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
        migrations.RemoveField(
            model_name='review',
            name='username',
        ),
    ]
