# Generated by Django 5.1.1 on 2024-09-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
